### ISSUE TITLE
Add option to delete an individual message.

### ISSUE THREAD

**Issue by srv-twry** [fossasia/susi_android#1081]
**Actual Behaviour**

Currently there are options to copy and share the message.

**Expected Behaviour**

There should also be an option to delete the message

**Steps to reproduce it**

Open ```ChatActivity``` and long press on any individual message. A dialog with options to copy and share will appear.

**LogCat for the issue**

NA

**Screenshots of the issue**

NA

**Would you like to work on the issue?**

Yes!

Both this and #1075 depends on where the chat's are stored i.e. on the server or in the database in the phone. If it is stored on the server, then it depends on whether the server supports deletion of messages.

@chiragw15 Your views ?

**Comment by chiragw15** [comment]
@srv-twry the delete option existed earlier. We had a discussion over it and decided to remove it because the messages were only getting deleted from the mobile local db and not the server. Since we wanted same messages on all the clients, we made this decision. If you want to implement the delete functionality in app, you'll have to first implement that on server i.e deleting a message from server should delete message from the server, thus making chat history consistent in all clients.

**Comment by srv-twry** [comment]
Thank you @chiragw15 . I'll see whether i can implement it on the server or not. If i can then i will reopen it. I am closing this issue for now.
