### ISSUE TITLE
Change of language in settings does not reflect

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1142]
**Actual Behaviour**

Currently, changing the language from default to any other language does not reflect in the app i.e. if the language id set to German (say), there is no change in the language in the app. I remains set to default.

**Expected Behaviour**

If the user sets the language to any other language in the settings, the app should display data in that language.

**Screenshots of the issue**

![language_change](https://user-images.githubusercontent.com/30979369/36852449-a6d89020-1d91-11e8-994d-9b3543e3cd7a.jpg)

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
As far as I could see this feature has not been implemented yet. Even the change in default system language is not reflected in our app.
I found this resource that we can use https://github.com/delight-im/Android-Languages
As of now, we send the language code as a query to the server. Other than that there has not been any implementation. Do you have any suggestions on how to implement this @batbrain7 @akshatnitd

**Comment by akshatnitd** [comment]
@arundhati24 For the web client, the multiple language support is implemented in the codebase by maintaining a file for all the different words used in the app. The implementation can be found [here](https://github.com/fossasia/chat.susi.ai/tree/master/src/components/Translate).

You can try to change he default system language and try to translate the words used within the app to that language. The language code that is sent as a query to the server is just to save the user state, so that whenever some user logs in, the default language can be set to it.

**Comment by arundhati24** [comment]
@akshatnitd That's true. I see there are no different files here. I will try to fix that first. Also, what we need is to implement the change of language from within the app. I checked Google Assistant. To change the language, it first directs us to the system language & input setting where we require to choose the language that we want. But, that way the system language is changed i.e. all the apps reflect the change of language. I think in our app the aim is to change the language for only our app. I doubt if that can be done because I think Android does not support that currently. If we wish to do that then we would have to localize them or use 3rd party tools. 
On a side note, currently, only a few languages are supported by Google Assistant as well.

**Comment by akshatnitd** [comment]
@arundhati24 Yes, correct. I think there needs to be a similar
implementation like the web chat.
