### ISSUE TITLE
FR: Include new dialog to encourage users to add a new app review in PlayStore

### ISSUE THREAD

**Issue by harshitbansal05** [fossasia/susi_android#1165]
It would be great to increase the number of app reviews in Play Store so that we can receive more feedback from our users.

The idea is to create a new dialog that would appear from time to time (we will think about the exact frequency), asking the users for a new review and redirect them to the PlayStore.

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@harshitbansal05  IMHO it is not a good idea to prompt the user from time to time (whether at higher or lower frequency) to add a review. I think it would not provide a good user experience. Also, if the user wishes to add a review or feedback, s/he can tap Rate SUSI option in the settings, which would direct the user to the play store.

**Comment by chiragw15** [comment]
The app is currently launched as beta. So, you can not add review afaik. Also prompting user to add review is stupid. It is not a money-earning app which needs reviews to get more users. Focus on more good functionalities like hotword detection, text to speech etc rather than this. So, closing this for now. Reopen if I am wrong.
