### ISSUE TITLE
Keyboard does not disappear after clicking cross on the SkillsActivity

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1244]
**Actual Behaviour**

Whenever we click on the search icon on the actionbar in SkillsActivity the softkeyboard pops up but it does not go away on clicking the cross icon.

**Expected Behaviour**

The keyboard should go away on clicking the cross icon

**Steps to reproduce it**

Open the skillsactivity and click on the search icon and then click on the cross icon.

**Would you like to work on the issue?**

Yes

**Comment by arundhati24** [comment]
@batbrain7 This cross icon is generally used to simply clear the content that has been typed in the search bar so that the user doesn't have to press the clear button repeatedly to clear the search bar content. It adds to the user experience. The keyboard should not disappear on pressing the cross icon. As a reference you can check this feature in the standard apps like WhatsApp or Telegram or maybe the Contacts app on your phone.
So IMHO it is fine.
But, what can be enhanced is that on tapping the cross icon, the cursor disappears and we see the SUSI.AI Skills label on the action bar. What should happen is that on tapping the cross icon, the content in the search bar should clear and the cursor should be visible i,e. the initial state on clicking the search icon should be restored.

**Comment by batbrain7** [comment]
@arundhati24 yeah I agree with you, will fix this soon
