### ISSUE TITLE
The pull to refresh is not disabled when skills are already being fetched.

### ISSUE THREAD

**Issue by akshatnitd** [fossasia/susi_android#1464]
**Actual Behaviour**
* The pull to refresh is not disabled when skills are already being fetched. It leads to multiple API calls and leads to request timeout. And the screen shows "unable to fetch data, please try again later"

**Expected Behaviour**
* The "pull to refresh"can be disabled while the interface is refreshing, so that the user can only refresh after the previous API call is completely handled.

**Steps to reproduce it**
Perform "Pull to Refresh" very quickly on the Skills Listing page.

**LogCat for the issue**
NA

**Screenshots of the issue**
NA

**Would you like to work on the issue?**
@arundhati24 , Can you work on it?

**Comment by arundhati24** [comment]
@batbrain7 Okay 👍

**Comment by codedsun** [comment]
@arundhati24 @batbrain7 Anyone of you working or i shall take it up?

**Comment by batbrain7** [comment]
@codedsun it seems @arundhati24 has already claimed it, I wanted to work on it but it is already taken. You may ask her

**Comment by codedsun** [comment]
@arundhati24 are you working?

**Comment by batbrain7** [comment]
The issue stated is the not the cause of the actual problem, the actual problem is very simple actually, once Unable to fetch is displayed due to some reason, we should swipe down to refresh the page and fetch the skills the UI, the cause is that UI is not updated properly on the fragment.

The problem that "Unable to fetch data" is displayed will only be rectified once the cumulative skills fetching API is integrated in the app. but for now I am fixing the issue such that if there is internet connectivity then on swiping down the page the UI is updated and displayed properly
