### ISSUE TITLE
Add feature to report a skill

### ISSUE THREAD

**Issue by arundhati24** [fossasia/susi_android#1530]
**Actual Behaviour**

Currently, there is no option to allow the user to report a skill.

**Expected Behaviour**

Add this option in the skill details screen.

**Would you like to work on the issue?**

Yes

**Comment by codedsun** [comment]
@arundhati24 As No work is shown, so I am sending a PR. Thanks

**Comment by arundhati24** [comment]
@codedsun First you should mention that you want to work on it. Follow best practices. You can't just do anything you like the way you want. I will send it when needed. Without attending the meetings and without knowing what to do next, please don't do just anything you like. I am closing the PR.

**Comment by codedsun** [comment]
@arundhati24 Thanks for closing the PR. Okay I have followed the best practices, but I eventually saw no replies from your side and either the replies were that you were working on it but still the issues are not resolved.

And wanted to ask that, what are issue trackers meant for? if the people can't work on it.I also saw no labels on the issues. I know you all are working hard and great! Kudos :+1: but do we have some opportunities to get something done?

I missed the meetings due to some unforeseen personal situation and tight deadlines. There are 77 issues currently open, but for the sake of PR no one's write a code.I am not refactoring code or changing the variables name and neither we are given to complete some deadlines.

And yes, we at open source work to promote awareness and support each other! rejecting someone's work without any acknowledgement only demotivates developers.

Sorry for the above activity!

**Comment by codedsun** [comment]
@arundhati24 You shall send the PR when needed 👍 
Thanks

**Comment by arundhati24** [comment]
@codedsun If it is open source, then please follow best practices. If I will not reply, any mentor will assign the issue to you. But, you should claim issues before sending PRs. I have no more comments to make. If you want to work on it, go ahead and reopen it but make sure you don't repeat this from next time. And, everybody has some or the other issues. So, if you missed the meetings, you can follow up on the agenda items later. And, nobody has rejected your work. I am not eligible to do so. But, you can't disrespect somebody by not following best practices of the community. Please reopen your PR and from the next time please claim the issues that somebody else has opened and claimed. There are other high priority items to work on, hence this was not yet worked upon.

**Comment by arundhati24** [comment]
And regarding labels, I will add them. I accept that should have been done. I am not working on everything, and will let you work if you let me know which issues you want to claim. But, the only point is please don't do things abruptly, do let people know that you want to work on something.

**Comment by codedsun** [comment]
@arundhati24 Sure, go on . Sorry for disrespecting the rules but no update has been shown since 23 days and there is no update on the issue tracker. 77 issues are still open, I know there are other priority works but my question was that which issues can we take over?
Too many issues in the issue tracker, I dont' think that you or @batbrain7 is working on all of them at the same time and giving update at the same time.

Every recent issues has claims but the activity is not shown and @mariobehling always says to reduce the no of issues in the issue tracker. So what shall that means? 
And this was a feature which was to be added, but yes I am taking other issues from now 👍 and will comment before working on it! 

My intention was only to speed up the development process and learn something, PR and commits count are not my part. I am focused for contributing towards the community. 🥂 
Thanks for the guidance :) 

PS : Rest it's your main time for the work, as these are final days of submission. Congo:)
