### ISSUE TITLE
Add layout to view connected devices

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1652]
**Actual Behaviour**

There is no layout for the devices section when the device is successfully connected to the server

**Expected Behaviour**

Add the layout to view connected devices.

**Would you like to work on the issue?**

Yes

**Comment by Bhavnaharitsa** [comment]
May I work on this issue ? @batbrain7 
Should the layout be on settings ?

**Comment by atm1504** [comment]
@stealthanthrax is there any way to know what (how many) susi devices are connected to my account from the server side? 
Because, currently what I have implemented is that, when we connect to a device from an app, we simply store that in our database, and shows it as connected devices. This data get erased as soon as the user logs out.

**Comment by stealthanthrax** [comment]
@atm , there was one endpoint present at the time of issue creation. Maybe someone from the web team can confirm the status. @akshatnitd ?
