### ISSUE TITLE
Unable To rate skill on Thumbs up/Down  icon

### ISSUE THREAD

**Issue by KaenDagger** [fossasia/susi_android#1738]
**Actual Behaviour**
Thumbs up/down icon in SUSI_MESSAGE Chat View displays Error Toast

**Expected Behaviour**

Thumbs up/Down icon should be highlighted

**Steps to reproduce it**
Click on Thumbs up/down icon in SUSI_MESSAGE Chat View 

**Screenshots of the issue**
<img src="https://user-images.githubusercontent.com/24780524/46908122-94b96c00-cf3b-11e8-9f93-6d7cbc8a1e31.png" width="360">

**Would you like to work on the issue?**
Yes

**Comment by arundhati24** [comment]
@theLimitBreaker I am unable to reproduce this issue. There is another issue #1756 related to this, which I have opened and will work upon. I think there might have been some connectivity issue due to which you encountered this error. You can try logging the response to check what is the actual cause of this error.

**Comment by atm1504** [comment]
@iamareebjamal @arundhati24 @mariobehling I cannot reproduce the issue. I, think this issue can be closed.
