### ISSUE TITLE
Feedback should be ordered by newest on top

### ISSUE THREAD

**Issue by chanmol1999** [fossasia/susi_android#2023]
**Describe the bug**
Currently when user gives a feedback on a skill its displayed at last in reviews .

**Expected Behaviour**
Instead feedback must be displayed in order such that newest one is on the  top inspite of the oldest on top such that user can also instantly see his feedback.

**Steps to reproduce it**
change in feedback activity 

**LogCat for the issue**

**Screenshots of the issue**

![gifreview](https://user-images.githubusercontent.com/42909612/54496969-4a3d8080-491b-11e9-828e-3944cea14b36.gif)

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Vivo Y83|
|Android Version  |8.1.0 |

**Would you like to work on the issue?**
Yes

**Comment by Bhavnaharitsa** [comment]
@iamareebjamal Can I take this up ?

**Comment by arundhati24** [comment]
Let me clarify this a bit. I see there are PRs and issues regarding the ordering of feedback items in the list.
So, first of all, I agree that the feedback list should have the newest feedback item on top of the list. But what we want is that if the user is logged in, her/his feedback, if she/he has provided any, should be on top of the list no matter what the time of submission is (check skills.susi.ai for this). In case, the user is not logged in, let the list be shown with the newest feedback item on top and similarly for all feedback items. Now, why these feedback items are being displayed in random order is because a user is allowed to edit her/his feedback. And, when this is done, there is no rearrangement of feedback items as per time in the response coming from the server. So, what becomes apparent is that there is neither ascending or descending order based on time.
I hope now it is clear what is going on. There is an existing issue #1388 for the feedback system. Please always check out existing issues to understand what has been going on.
Please ask questions and get clarifications if you all are not clear about any particular feature before making changes because Android client is not implementing features as per its own convenience. All the clients will have similar implementations.

**Comment by arundhati24** [comment]
So, if somebody wants to work on this feature please have a look at #1388 and see what has been done and what has yet to be done. Also, you can check out skills.susi.ai to see how this has been implemented. For now, the user is not able to edit her/his feedback from the Android app. And yes, the order of feedback has to be maintained as I explained above. So, these are some of the things that have to be worked upon when it comes to feedback.

**Comment by atm1504** [comment]
@arundhati24 @iamareebjamal  as much as I understood what should we do is that:
- First, display the feedback provided by the user (if it exists)
- Then arrange the rest according to the newest at the top.

If, thats the thing then can I start implementing it logically in the android side?
