### ISSUE TITLE
App crashed on clicking picture in edittext(left) (in mainactivity)

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#34]

**Comment by betterclever** [comment]
@amitiwary999 Please post logs of the crash here.

**Comment by betterclever** [comment]
@the-dagger @daminisatya @Orbiter  The cause of the issue is when ListView was updated with recyclerView in #13 the possibility of sending images was removed. But the point is whether app needs to send images or not, if not that can be removed completely or in future if something like that is needed, we may add the functionality similar to what was present earlier.

**Comment by addiittya2006** [comment]
@betterclever I don't think we ever had any functionality for sending images.
@daminisatya Susi Server doesn't have support for Images, right?

This Error is basically caused by a Nullable OnClick event fired with No Action.

**Comment by betterclever** [comment]
@addiittya2006 Actually, I was referring to the image support in the library itself from which the project was forked, it included support for sending images , not sending actually, just displaying images in the views and for its demo, a button with a functionality that if you'll click that, the avatar image of other person is shown as a reply ( for demo purposes ). I was skeptical about leaving that since we may add support for stickers or related (maybe) in future.
