### ISSUE TITLE
Delete splash screen in order to come closer to our goal of a continuous personal assistant

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#385]
**Actual Behaviour**

Currently Susi has a splash screen. The splash screen does not provide any functionality. The future goal of the Susi app is to make it run continuously in the background and provide answers to users through hot words. Therefore if we can get rid of the splash screen we will come closer to this goal.

**Expected Behaviour**

No splash screen in the app and any features running in the background of the splash screen becoming independent of the splash screen.

**Comment by amitiwary999** [comment]
I would like to work on this issue

**Comment by bxute** [comment]
Adding splash screen the way done before is totally un-acceptable for continuous responsive behavior due to time taken for executing the lifecycle and setting content views for the activity.
Point of adding a visual feedback at cost of no more execution time/load latency was for substituting blank screen whenever it loads.

At some point of time user needs to open the app, else it should have been a background service.

It can be achieved by simply setting a pseudo-activity before the expected launcher,
by pseudo-activity i mean it will not set its content(time-taking due to view inflation) and will start launcher asap.

for ref. any of the google product can be tapped on and you will notice time taken for first view is just equal to time to load first launcher, no extraa overload..
