### ISSUE TITLE
Opening applications(like facebook, twitter and important apps on android) on query

### ISSUE THREAD

**Issue by AliAyub007** [fossasia/susi_android#589]
**Actual Behaviour**

Right now it doesn't open any application on query

**Expected Behaviour**

On query like open Facebook or launch chrome it should open these applications. 

**Steps to reproduce it**

creating intents for applications and launching them. 

**Screenshots of the issue**

**Would you like to work on the issue?**

Yes I would like to work on it.

**Comment by chiragw15** [comment]
@AliAyub007 Please don't hardcode the feature in app itself. The query should be sent to server and the action must be taken according to the response from server. I think, there is no point in writing code like `if(query.contains("open facebook") { openFacebook(); }` . A proper flow of sending query to server and implementing feature in the app according to the response of the server should be followed. What say? @mariobehling @Orbiter What do you think about this?

**Comment by AliAyub007** [comment]
@chiragw15  Right now there is an option of send mail it is hard coded and secondly in these actions we don't need that kind of response from server and only those app needed to be launched. Still @mariobehling  and @Orbiter kindly guide about this.

**Comment by chiragw15** [comment]
@AliAyub007 There is not just sending email feature in app, there are many more like calling, playing a video, setting a reminder etc. They all are currently hardcoded. We have to shift these features to the server. The launching part will be done by app but the understanding of the query has to be done by the server. There is no use of server if you are not even sending query to it. Like take query "where is singapore" for an example. http://api.asksusi.com/susi/chat.json?timezoneOffset=-330&q=where+is+singapore There is a "type" in response which is 'anchor' for this query. It helps understanding the app what it has to do. Then accordingly the app displays the map because server has reponded in that way. We could have hardcoded that query and displayed that in maps. For other normal queries like http://api.asksusi.com/susi/chat.json?timezoneOffset=-330&q=hi the "type" is 'answer' which indicates that the app has to just response to query as text and has to do nothing else. Similarly for every feature we want to add, we should add that to the server and send the response to app telling it what to do. This is what I think we should do. @mariobehling @Orbiter can guide with actual plans.

**Comment by amitiwary999** [comment]
@chiragw15 you are right.

**Comment by mayank408** [comment]
Not required for now
