### ISSUE TITLE
Linkify Links

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#62]
Currently some answers generate links, but these are not clickable.

**Comment by gogeta95** [comment]
I'd like to work on this, please assign it to me. thanks.

**Comment by daminisatya** [comment]
@gogeta95 Feel free to assign issues which you can.

**Comment by gogeta95** [comment]
I don't have the authority to do so.

**Comment by gogeta95** [comment]
@mariobehling  should we linkify only Susi responses or also the links sent be user? (if any)

**Comment by daminisatya** [comment]
@gogeta95  Only responses.

**Comment by gogeta95** [comment]
I started working on this but the links  aren't visible properly because of colors. what color shall we pick for links? I'd suggest #FF6D00 (Orange). attaching both.
![screenshot from 2016-09-30 17-16-32](https://cloud.githubusercontent.com/assets/8329096/18990851/76ffdaf8-8732-11e6-87ee-13863ad67a53.png)

![screenshot from 2016-09-30 17-21-42](https://cloud.githubusercontent.com/assets/8329096/18990857/83b86576-8732-11e6-83a9-57d1329fdc60.png)

**Comment by daminisatya** [comment]
The chat bubble color is too heavy! Can't we change the colors as in susi webclient? 

![sdfhd](https://cloud.githubusercontent.com/assets/6227784/18991081/f504a608-8733-11e6-81ce-bbb71de8e37c.PNG)

**Comment by gogeta95** [comment]
I guess we should keep same colors in web and Android to keep uniformity.

**Comment by daminisatya** [comment]
Cool, then use the colors from the web client.
