### ISSUE TITLE
UI issue with input text field

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#665]
**Actual Behaviour**

The width of frame layout in which there is an edit text to enter query in the main activity is set to wrap_content. 

**Expected Behaviour**
Change it to match_parent.
Also, the edit text height doesn't increase on adding more than 1 lines. Make it expand upto 4 lines.

**Steps to reproduce it**

Enter a very long query in edit text of main activity.

**Comment by Muks14x** [comment]
Is this issue fixed already, or can I try to help with it? I gave it a try, and seem to have fixed it (as specified) with a couple of small changes.

**Comment by chiragw15** [comment]
Sure, go ahead and send a PR. This is not fixed yet. Assigning it to you.

**Comment by Muks14x** [comment]
Had to do  EditText height change in the init() function in MainActivity, since the XML attribute for the same were [getting ignored](https://stackoverflow.com/questions/31679865/edittext-with-word-wrap-without-line-breaks-and-with-keyboard-action-set-to-n) for some reason when I tried. Is this the correct way to do it?

**Comment by chiragw15** [comment]
There should not be any problem with that. If it works, send a PR. I'll review it.
