### ISSUE TITLE
Make different POJO classes for each action type and use inheritance.

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#671]
**Actual Behaviour**

Right now we only have one class for every action type : https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/rest/responses/susi/Action.java .

**Expected Behaviour**

Break it into parts for each action type.

@betterclever Can you add more detail to this issue.

**Comment by betterclever** [comment]
Good Point.
Since all action types have different fields, we should not have a single class for them but inheritance must be used.
Parent Class: Action
Child Classes: MapAction, AnswerAction, AnchorAction, TableAction and so on.

A similar implementation has been adopted in Susi Python Library. Check [here](https://github.com/fossasia/susi_api_wrapper/blob/master/python_wrapper/susi_python/models.py)

Now, probelm comes while using Retrofit while using Inheritance. Problem being when Retrofit instance is being created here, you need to supply a custom converter since Retrofit will try to parse each action to Action Class and not subclass by default. 
You can do so by overriding GSON Converter. See this StackOverflow answer for clarity. 
https://stackoverflow.com/questions/35502079/custom-converter-for-retrofit-2

**Comment by amitiwary999** [comment]
@chiragw15 what should be kept in parent action class?

**Comment by betterclever** [comment]
The type is not needed altogether. It will be clear from subclass. 'expression' is specific to AnswerAction type and can't be included in the Parent Class.
The Parent Class has no data field. It will be an empty class to enforce inheritance to be able to refer action types in an answer by a single List<Action> object.
I hope, I am clear.
I suggest, you going through the Python Implementation referred above once too for more clarity.
Thanks.

**Comment by codedsun** [comment]
@chiragw15  can I work on this issue?

**Comment by batbrain7** [comment]
I am working on this issue @chiragw15 , will send a PR soon
