### ISSUE TITLE
Redirecting to the sign in page after the user signs up. (The user log in should be automatic/pre-initialized after the user signs up.)

### ISSUE THREAD

**Issue by AkashIsCoding** [fossasia/susi_android#686]
**Actual Behaviour**

After you sign up it redirects you to the sign in page. The issue is not yet over there is also a problem in (log in) it says password error.

**Expected Behaviour**

It should automatically log you in after you sign up.

**Would you like to work on the issue?**
Yes.

**Comment by chiragw15** [comment]
@AkashIsCoding Whenever you sign up, you do get a dialog box saying like "You have successfully signed up, we have send a mail. Please check your mail to confirm your account" ? This means we can not directly "automatically log you in after you sign up." because the account needs to be confirmed. Once you confirm the account by clicking on the link sent to your email, you can come back to app and login again. You will be able to login. Try it once.

**Comment by chiragw15** [comment]
"We have sent an email to the address you provided. Please use the confirmation link to activate your account and sign in to susi" . This is the exact message on dialog box.

**Comment by chiragw15** [comment]
@AkashIsCoding here also. If you think, I got the issue wrong, then please explain it a bit else according to me no need for this. But we are thinking of adding deep links in app. @mayank408 @amitiwary999 What do you guys think?

**Comment by AkashIsCoding** [comment]
Yes, confirmation mail makes it much more secure. But I found a glitch in
the web searches, the data which it shows is incomplete.

**Comment by chiragw15** [comment]
@AkashIsCoding can you please open an issue about it with a little detail. Thanks.
