### ISSUE TITLE
Implement an Anonymous Mode

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#730]
Some time ago we started to request users to login. This has worked out for some, but actually the solution has not reached production and we should take a step back.

Please change as follows:
When the app starts open the app in anonymous mode and provide a button in the menu to login as before.

**Comment by amitiwary999** [comment]
I want to work on this.

**Comment by chiragw15** [comment]
Okay, an idea which can be useful.

Instead of directly starting the app in anonymous mode, why don't we add an option to skip login in login screen. And if user skips login, add an option in menu to login. I made an app for an event some time ago. It follows the same thing.

See, there is a "skip" option in the bottom. When the app is installed, this screen is displayed only for the first run. After that this screen is only shown when a user clicks on login button in the menu.
![screenshot_20170618-145448](https://user-images.githubusercontent.com/16978820/27259718-1b534212-5437-11e7-8a2c-f5b9b0d38e6c.png)

Now If the user clicks on skip, the main screen is shown with the login option on top. User can click on the "login" option which will open the above login screen. 
![screenshot_20170618-145519](https://user-images.githubusercontent.com/16978820/27259728-4bf265d8-5437-11e7-8d3d-4af91a04bd3c.png)

@mariobehling @mayank408 @amitiwary999 @betterclever Views on this? https://play.google.com/store/apps/details?id=in.ac.iitp.anwesha2k17&hl=en This is the link of the app on play store if you want to test the flow.

**Comment by amitiwary999** [comment]
Yes many app has this feature.  I also tried it in one app.

**Comment by mayank408** [comment]
@mariobehling @chiragw15 We could add an option like "Enter without login" in the login screen.

**Comment by chashmeetsingh** [comment]
Yup, that would be a nice option to include.

**Comment by mariobehling** [comment]
Yes, good idea. Just add a skip button for now on Login Page. The sign up page does not need a skip button. I think only login page.

**Comment by mayank408** [comment]
@mariobehling Yes 'skip' button will only be included in Login page.

**Comment by amitiwary999** [comment]
@mariobehling I implemented it [here](https://github.com/fossasia/susi_android/pull/732)
